const pool = require('../config/db');

// CET-4 + CET-6 核心词汇库（共约 650 词，覆盖全字母 A-Z）
const words = [
  // === A (四级) ===
  ['abandon', '抛弃，放弃'], ['ability', '能力，才能'], ['abnormal', '不正常的，异常的'],
  ['aboard', '在船/飞机/车上'], ['abolish', '废除，取消'], ['abroad', '到国外，在国外'],
  ['absence', '缺席，不在场'], ['absolute', '绝对的，完全的'], ['absorb', '吸收，吸引'],
  ['abstract', '抽象的，摘要'], ['abundant', '丰富的，充裕的'], ['abuse', '滥用，虐待'],
  ['academic', '学术的，学院的'], ['academy', '学院，研究院'], ['accelerate', '加速，促进'],
  ['access', '进入，通道，访问'], ['accommodation', '住宿，膳宿'], ['accompany', '陪伴，伴随'],
  ['accomplish', '完成，实现'], ['account', '账户，说明，解释'], ['accumulate', '积累，积聚'],
  ['accurate', '准确的，精确的'], ['accuse', '指控，指责'], ['achieve', '达到，实现'],
  ['achievement', '成就，成绩'], ['acknowledge', '承认，确认'], ['acquire', '获得，习得'],
  ['adapt', '适应，改编'], ['adequate', '足够的，适当的'], ['adjust', '调整，适应'],
  ['administration', '管理，行政'], ['admire', '钦佩，赞赏'], ['admission', '准许进入，承认'],
  ['adopt', '采用，收养'], ['advance', '前进，进步'], ['advanced', '高级的，先进的'],
  ['advantage', '优势，有利条件'], ['adventure', '冒险，奇遇'], ['advertise', '做广告，宣传'],
  ['advocate', '提倡，倡导'], ['affair', '事务，事件'], ['affect', '影响，感动'],
  ['afford', '负担得起，提供'], ['aggressive', '侵略的，好斗的'], ['agreement', '协议，协定'],
  ['agriculture', '农业'], ['aircraft', '飞机，飞行器'], ['alcohol', '酒精，乙醇'],
  ['alter', '改变，修改'], ['alternative', '替代的，供替代的选择'], ['altitude', '海拔，高度'],
  ['amaze', '使惊奇'], ['ambassador', '大使'], ['ambiguous', '模棱两可的'],
  ['ambition', '雄心，野心'], ['ambitious', '有雄心的，野心勃勃的'], ['amount', '数量，总额'],
  ['ample', '充足的，丰富的'], ['amuse', '逗乐，娱乐'], ['analysis', '分析，解析'],
  ['ancestor', '祖先，祖宗'], ['anchor', '锚，主持'], ['ancient', '古代的，古老的'],
  ['anniversary', '周年纪念日'], ['announce', '宣布，通告'], ['annoy', '使恼怒，打扰'],
  ['annual', '每年的，年度的'], ['anticipate', '预期，期望'], ['anxiety', '焦虑，忧虑'],
  ['apart', '分开地，相隔'], ['apartment', '公寓'], ['apologize', '道歉，认错'],
  ['apparent', '明显的，表面上的'], ['appeal', '呼吁，吸引，上诉'], ['appetite', '食欲，胃口'],
  ['applaud', '鼓掌，称赞'], ['appliance', '电器，器具'], ['applicant', '申请人'],
  ['application', '申请，应用'], ['apply', '申请，应用'], ['appoint', '任命，约定'],
  ['appointment', '任命，约会'], ['appreciate', '欣赏，感激'], ['approach', '方法，接近'],
  ['appropriate', '适当的，恰当的'], ['approval', '批准，赞成'], ['approve', '批准，赞成'],
  ['arbitrary', '任意的，武断的'], ['architect', '建筑师'], ['architecture', '建筑学，建筑风格'],
  ['argue', '争论，辩论'], ['argument', '论据，争论'], ['arise', '出现，产生'],
  ['arouse', '唤醒，激起'], ['arrange', '安排，整理'], ['arrest', '逮捕，阻止'],
  ['artificial', '人造的，虚假的'], ['artist', '艺术家'], ['artistic', '艺术的'],
  ['ashamed', '羞愧的，惭愧的'], ['aspect', '方面，层面'], ['assemble', '集合，组装'],
  ['assert', '断言，宣称'], ['assess', '评估，评定'], ['asset', '资产，优点'],
  ['assign', '分配，指派'], ['assist', '帮助，协助'], ['assistance', '帮助，援助'],
  ['associate', '联系，关联，同事'], ['association', '协会，社团'], ['assume', '假设，承担'],
  ['assumption', '假设，设想'], ['assure', '保证，使确信'], ['atmosphere', '大气，气氛'],
  ['atom', '原子'], ['attach', '附上，系上'], ['attain', '达到，获得'],
  ['attempt', '尝试，企图'], ['attend', '出席，参加'], ['attention', '注意，注意力'],
  ['attitude', '态度，看法'], ['attract', '吸引'], ['attraction', '吸引力，景点'],
  ['attractive', '有吸引力的'], ['attribute', '属性，归因于'], ['audience', '观众，听众'],
  ['author', '作者'], ['authority', '权威，当局'], ['available', '可用的，有效的'],
  ['avenue', '大街，途径'], ['average', '平均的，普通的'], ['avoid', '避免，回避'],
  ['award', '奖励，奖品'], ['aware', '意识到的，知道的'], ['awful', '糟糕的，可怕的'],
  ['awkward', '尴尬的，笨拙的'],

  // === B (四六级) ===
  ['bachelor', '学士，单身汉'], ['background', '背景，经历'], ['backward', '向后的，落后的'],
  ['bacteria', '细菌'], ['balance', '平衡，余额'], ['ban', '禁止，禁令'],
  ['bankrupt', '破产的'], ['bargain', '便宜货，讨价还价'], ['barrier', '障碍，屏障'],
  ['battery', '电池'], ['battle', '战斗，战役'], ['bear', '忍受，承担，熊'],
  ['behalf', '代表，利益'], ['behave', '行为，表现'], ['behavior', '行为，举止'],
  ['belief', '信念，信仰'], ['beloved', '心爱的，被爱的'], ['beneath', '在…之下'],
  ['beneficial', '有益的，有利的'], ['benefit', '益处，好处，受益'], ['besides', '此外，除…之外'],
  ['betray', '背叛，出卖'], ['beyond', '超越，在…之外'], ['bid', '出价，投标'],
  ['bind', '捆绑，约束'], ['biography', '传记'], ['biology', '生物学'],
  ['bitter', '苦的，痛苦的'], ['blame', '责备，责怪'], ['blank', '空白的，茫然的'],
  ['blast', '爆炸，一阵'], ['bleed', '流血'], ['blend', '混合，融合'],
  ['bless', '祝福，保佑'], ['block', '街区，阻塞，块'], ['bloom', '开花，繁荣'],
  ['board', '董事会，木板，登上'], ['boast', '吹嘘，自夸'], ['bold', '大胆的，粗体的'],
  ['bomb', '炸弹，轰炸'], ['bond', '纽带，债券，结合'], ['bonus', '奖金，红利'],
  ['boom', '繁荣，激增'], ['border', '边界，边境'], ['bore', '使厌烦，钻孔'],
  ['bother', '打扰，麻烦'], ['bounce', '弹跳，反弹'], ['bound', '必然的，有约束的'],
  ['boundary', '边界，分界线'], ['brand', '品牌，商标'], ['breed', '品种，繁殖'],
  ['brief', '简短的，摘要'], ['brilliant', '杰出的，明亮的'], ['broadcast', '广播，播送'],
  ['browse', '浏览'], ['budget', '预算'], ['burden', '负担，重担'],
  ['bureau', '局，处，办公室'], ['burst', '爆裂，突发'], ['bury', '埋葬，掩埋'],

  // === C (四六级) ===
  ['cabinet', '橱柜，内阁'], ['calculate', '计算，估计'], ['campaign', '运动，战役'],
  ['capable', '有能力的'], ['capacity', '容量，能力'], ['capture', '捕获，俘获'],
  ['carbon', '碳'], ['career', '职业，生涯'], ['cargo', '货物'],
  ['carve', '雕刻，切开'], ['cast', '投掷，铸造，演员阵容'], ['casual', '随便的，偶然的'],
  ['catalog', '目录'], ['category', '类别，种类'], ['caution', '谨慎，警告'],
  ['cautious', '谨慎的，小心的'], ['cease', '停止，终止'], ['celebrate', '庆祝，赞美'],
  ['celebration', '庆祝，庆典'], ['cell', '细胞，小牢房'], ['certificate', '证书，执照'],
  ['challenge', '挑战，质疑'], ['champion', '冠军，拥护者'], ['channel', '频道，渠道，海峡'],
  ['chaos', '混乱，混沌'], ['chapter', '章，章节'], ['character', '性格，角色，字符'],
  ['characteristic', '特征，特性'], ['charge', '收费，控告，充电'], ['charity', '慈善，慈善机构'],
  ['chart', '图表，海图'], ['chase', '追逐，追赶'], ['chemical', '化学的，化学品'],
  ['cherish', '珍惜，珍爱'], ['chief', '主要的，首领'], ['chip', '芯片，碎片'],
  ['choke', '窒息，噎住'], ['circuit', '电路，环路'], ['circulate', '循环，流通'],
  ['circumstance', '环境，情况'], ['citizen', '公民，市民'], ['civil', '公民的，文明的，民事的'],
  ['civilization', '文明，文化'], ['claim', '声称，索赔'], ['clarify', '澄清，阐明'],
  ['clash', '冲突，撞击'], ['classic', '经典的，名著'], ['classify', '分类，归类'],
  ['client', '客户，委托人'], ['climate', '气候，风气'], ['clinic', '诊所'],
  ['coach', '教练，辅导'], ['collapse', '倒塌，崩溃'], ['colleague', '同事'],
  ['collection', '收集，收藏品'], ['collision', '碰撞，冲突'], ['colony', '殖民地，群体'],
  ['column', '栏目，柱子，专栏'], ['combat', '战斗，格斗'], ['combine', '结合，联合'],
  ['command', '命令，指挥'], ['comment', '评论，意见'], ['commerce', '商业，贸易'],
  ['commercial', '商业的，广告'], ['commission', '委员会，佣金，委托'], ['commit', '犯罪，承诺，提交'],
  ['commitment', '承诺，投入'], ['communicate', '交流，沟通'], ['community', '社区，团体'],
  ['companion', '同伴，伙伴'], ['comparable', '可比较的，类似的'], ['compare', '比较，对比'],
  ['comparison', '比较，对照'], ['compass', '指南针，圆规'], ['compel', '强迫，迫使'],
  ['compensate', '补偿，赔偿'], ['compete', '竞争，比赛'], ['competition', '竞争，比赛'],
  ['competitive', '有竞争力的'], ['complain', '抱怨，投诉'], ['complaint', '投诉，抱怨'],
  ['complex', '复杂的，综合体'], ['complicated', '复杂的，难懂的'], ['component', '组成部分，部件'],
  ['compose', '组成，创作'], ['composition', '作文，成分'], ['comprehend', '理解，领悟'],
  ['comprehensive', '全面的，综合的'], ['comprise', '包含，由…组成'], ['compromise', '妥协，折中'],
  ['conceal', '隐藏，隐瞒'], ['concentrate', '集中，专注'], ['concept', '概念，观念'],
  ['concern', '关心，担忧'], ['conclude', '得出结论，结束'], ['conclusion', '结论，结尾'],
  ['concrete', '具体的，混凝土'], ['condition', '条件，状况'], ['conduct', '行为，进行，指挥'],
  ['conference', '会议，讨论会'], ['confess', '坦白，承认'], ['confidence', '信心，信任'],
  ['confident', '自信的'], ['confine', '限制，局限'], ['confirm', '确认，证实'],
  ['conflict', '冲突，矛盾'], ['confront', '面对，对抗'], ['confuse', '使困惑，混淆'],
  ['congress', '国会，代表大会'], ['conjunction', '连接，连词'], ['connect', '连接，联系'],
  ['connection', '连接，关系'], ['conquer', '征服，战胜'], ['conscience', '良心，良知'],
  ['conscious', '有意识的，清醒的'], ['consequence', '结果，后果'], ['conservative', '保守的'],
  ['consider', '考虑，认为'], ['considerable', '相当大的，可观的'], ['considerate', '体贴的，考虑周到的'],
  ['consideration', '考虑，体贴'], ['consist', '由…组成，在于'], ['consistent', '一致的，始终如一的'],
  ['constant', '不断的，常数'], ['constitute', '构成，组成'], ['constitution', '宪法，章程'],
  ['construct', '建造，构建'], ['construction', '建设，建筑'], ['consult', '咨询，查阅'],
  ['consume', '消费，消耗'], ['consumer', '消费者'], ['consumption', '消费，消耗'],
  ['contact', '联系，接触'], ['contain', '包含，容纳'], ['contemporary', '当代的，同时代的'],
  ['contempt', '轻视，蔑视'], ['content', '内容，满意的'], ['contest', '竞赛，比赛'],
  ['context', '上下文，背景'], ['continual', '持续的，频繁的'], ['continuous', '连续的，不间断的'],
  ['contract', '合同，收缩'], ['contrary', '相反的，对立的'], ['contrast', '对比，对照'],
  ['contribute', '贡献，捐献'], ['contribution', '贡献，捐献'], ['controversial', '有争议的'],
  ['convenience', '方便，便利'], ['convenient', '方便的，便利的'], ['convention', '惯例，大会'],
  ['convey', '传达，运送'], ['convince', '说服，使信服'], ['cooperate', '合作，协作'],
  ['coordinate', '协调，坐标'], ['cope', '应对，处理'], ['core', '核心，要点'],
  ['corporate', '公司的，法人的'], ['corporation', '公司，企业'], ['correspond', '对应，通信'],
  ['corruption', '腐败，贪污'], ['council', '委员会，理事会'], ['counsel', '劝告，法律顾问'],
  ['counter', '柜台，反驳'], ['courage', '勇气，胆量'], ['court', '法庭，球场'],
  ['crash', '坠毁，碰撞'], ['create', '创造，创建'], ['creative', '创造性的，有创意的'],
  ['creature', '生物，动物'], ['credit', '信用，学分，赞扬'], ['crew', '全体船员，工作人员'],
  ['crime', '犯罪，罪行'], ['criminal', '罪犯，犯罪的'], ['crisis', '危机，紧要关头'],
  ['critical', '批评的，关键的'], ['criticism', '批评，评论'], ['criticize', '批评，评论'],
  ['crucial', '至关重要的'], ['cultivate', '培养，耕作'], ['culture', '文化，教养'],
  ['curiosity', '好奇心'], ['curious', '好奇的'], ['currency', '货币，流通'],
  ['current', '当前的，水流'], ['curriculum', '课程'], ['curve', '曲线，弯曲'],
  ['cushion', '垫子，缓冲'], ['custom', '习俗，习惯'], ['cynical', '愤世嫉俗的'],

  // === D (四六级) ===
  ['damage', '损害，破坏'], ['damp', '潮湿的'], ['deadline', '截止日期'],
  ['debate', '辩论，争论'], ['debt', '债务，欠款'], ['decade', '十年'],
  ['decay', '腐烂，衰退'], ['deceive', '欺骗，蒙骗'], ['declare', '宣布，声明'],
  ['decline', '下降，拒绝'], ['decorate', '装饰，装修'], ['decrease', '减少，降低'],
  ['defeat', '击败，战胜'], ['defect', '缺陷，缺点'], ['defend', '防御，辩护'],
  ['define', '定义，界定'], ['definite', '明确的，确定的'], ['definition', '定义，释义'],
  ['delegate', '代表，委派'], ['delete', '删除'], ['deliberate', '故意的，深思熟虑的'],
  ['delicate', '精致的，微妙的'], ['deliver', '递送，发表'], ['delivery', '递送，交付'],
  ['demand', '需求，要求'], ['democracy', '民主，民主制度'], ['demonstrate', '证明，演示'],
  ['dense', '密集的，稠密的'], ['deny', '否认，拒绝'], ['depart', '出发，离开'],
  ['department', '部门，系'], ['departure', '离开，出发'], ['depend', '依赖，依靠'],
  ['dependent', '依赖的，从属的'], ['deposit', '存款，押金，沉积'], ['depress', '使沮丧，使萧条'],
  ['depression', '抑郁，萧条'], ['derive', '源自，获得'], ['describe', '描述，形容'],
  ['description', '描述，说明'], ['deserve', '值得，应得'], ['design', '设计，图案'],
  ['desirable', '可取的，令人满意的'], ['desire', '渴望，欲望'], ['despair', '绝望'],
  ['desperate', '绝望的，不顾一切的'], ['despite', '尽管，不管'], ['destination', '目的地'],
  ['destroy', '破坏，摧毁'], ['destruction', '破坏，毁灭'], ['detail', '细节，详情'],
  ['detect', '发现，察觉'], ['detective', '侦探'], ['determination', '决心，决定'],
  ['determine', '决定，确定'], ['develop', '发展，开发'], ['device', '设备，装置'],
  ['devise', '设计，发明'], ['devote', '致力于，奉献'], ['dial', '拨号，刻度盘'],
  ['dictate', '口述，命令'], ['differ', '不同，有区别'], ['digest', '消化，摘要'],
  ['digital', '数字的，数码的'], ['dignity', '尊严，高贵'], ['dilemma', '困境，两难'],
  ['dimension', '尺寸，维度'], ['diploma', '文凭，毕业证书'], ['diplomatic', '外交的，有策略的'],
  ['disaster', '灾难，灾害'], ['discard', '丢弃，抛弃'], ['discharge', '排放，解雇'],
  ['discipline', '纪律，学科'], ['discount', '折扣'], ['discriminate', '歧视，区分'],
  ['disguise', '伪装，掩饰'], ['dismiss', '解雇，解散'], ['disorder', '混乱，失调'],
  ['display', '展示，显示'], ['dispose', '处理，处置'], ['dispute', '争论，纠纷'],
  ['dissolve', '溶解，解散'], ['distinct', '明显的，不同的'], ['distinguish', '区分，辨别'],
  ['distract', '分散，使分心'], ['distribute', '分配，分发'], ['district', '地区，区域'],
  ['disturb', '打扰，扰乱'], ['diverse', '多样的，不同的'], ['divorce', '离婚，分离'],
  ['document', '文件，文档'], ['domestic', '国内的，家庭的'], ['dominate', '主导，支配'],
  ['donate', '捐赠，捐献'], ['donation', '捐赠，捐款'], ['doubt', '怀疑，疑问'],
  ['download', '下载'], ['draft', '草稿，起草'], ['drain', '排水，耗尽'],
  ['drama', '戏剧，剧本'], ['dramatic', '戏剧性的，引人注目的'], ['drift', '漂流，趋势'],
  ['drown', '淹死，淹没'], ['durable', '耐用的，持久的'], ['duration', '持续时间'],
  ['dynamic', '动态的，有活力的'],

  // === E (四六级) ===
  ['eager', '渴望的，热切的'], ['earnest', '认真的，诚恳的'], ['earthquake', '地震'],
  ['ease', '容易，舒适，缓和'], ['economic', '经济的，经济学的'], ['economy', '经济，节约'],
  ['edition', '版本，版次'], ['editor', '编辑，编者'], ['educate', '教育，培养'],
  ['effective', '有效的，生效的'], ['efficiency', '效率，效能'], ['efficient', '效率高的'],
  ['elaborate', '精心制作的，详尽的'], ['elect', '选举，选择'], ['election', '选举'],
  ['electronic', '电子的'], ['elegant', '优雅的，精致的'], ['element', '元素，要素'],
  ['elementary', '基本的，初级的'], ['eliminate', '消除，淘汰'], ['embarrass', '使尴尬'],
  ['embrace', '拥抱，包含'], ['emerge', '出现，浮现'], ['emergency', '紧急情况'],
  ['emission', '排放，散发'], ['emotion', '情感，情绪'], ['emotional', '情感的，情绪化的'],
  ['emphasis', '强调，重点'], ['emphasize', '强调，着重'], ['employ', '雇用，使用'],
  ['employee', '雇员'], ['employer', '雇主'], ['employment', '就业，雇用'],
  ['enable', '使能够，启用'], ['enclose', '围住，附上'], ['encounter', '遇到，遭遇'],
  ['encourage', '鼓励，激励'], ['endeavor', '努力，尽力'], ['endure', '忍受，持续'],
  ['enforce', '执行，强制'], ['engage', '从事，订婚，吸引'], ['engine', '发动机，引擎'],
  ['enhance', '增强，提高'], ['enormous', '巨大的，庞大的'], ['ensure', '确保，保证'],
  ['enterprise', '企业，事业'], ['entertain', '娱乐，招待'], ['enthusiasm', '热情，热心'],
  ['enthusiastic', '热情的，热心的'], ['entitle', '给…权利，题名'], ['entrepreneur', '企业家'],
  ['entry', '进入，入口'], ['environment', '环境'], ['envy', '嫉妒，羡慕'],
  ['epidemic', '流行病，流行的'], ['episode', '插曲，一集'], ['equal', '平等的，等于'],
  ['equip', '装备，配备'], ['equivalent', '等价的，相等的'], ['era', '时代，纪元'],
  ['error', '错误，误差'], ['erupt', '爆发，喷发'], ['escape', '逃跑，逃避'],
  ['essential', '必要的，本质的'], ['establish', '建立，设立'], ['estate', '房地产，庄园'],
  ['estimate', '估计，估算'], ['evaluate', '评估，评价'], ['eventually', '最终，终于'],
  ['evidence', '证据，证明'], ['evident', '明显的，明白的'], ['evil', '邪恶的，罪恶'],
  ['evolution', '进化，演变'], ['evolve', '发展，进化'], ['exaggerate', '夸张，夸大'],
  ['examine', '检查，考试'], ['exceed', '超过，超越'], ['exception', '例外，除外'],
  ['excess', '过量，过度'], ['excessive', '过度的，过多的'], ['exchange', '交换，兑换'],
  ['excite', '使兴奋，激发'], ['exclude', '排除，排斥'], ['exclusive', '独有的，排他的'],
  ['execute', '执行，处决'], ['executive', '行政的，高管'], ['exert', '施加，运用'],
  ['exhibit', '展览，展示'], ['existence', '存在，生存'], ['expand', '扩展，膨胀'],
  ['expansion', '扩张，膨胀'], ['expect', '期待，预期'], ['expectation', '期望，预期'],
  ['expense', '花费，代价'], ['experiment', '实验，试验'], ['expert', '专家，内行'],
  ['explain', '解释，说明'], ['explicit', '明确的，清楚的'], ['exploit', '开发，剥削'],
  ['explore', '探索，探究'], ['explosion', '爆炸，激增'], ['export', '出口，输出'],
  ['expose', '暴露，揭露'], ['exposure', '暴露，曝光'], ['extend', '延伸，扩展'],
  ['extension', '延伸，扩展名'], ['extensive', '广泛的，大量的'], ['extent', '程度，范围'],
  ['external', '外部的，外面的'], ['extinguish', '熄灭，扑灭'], ['extraordinary', '非凡的，特别的'],
  ['extreme', '极端的，极度的'],

  // === F (四六级) ===
  ['fabric', '织物，结构'], ['facilitate', '促进，使便利'], ['facility', '设施，设备'],
  ['factor', '因素，因子'], ['faculty', '院系，能力'], ['fade', '褪色，逐渐消失'],
  ['faith', '信仰，信任'], ['faithful', '忠诚的，忠实的'], ['fame', '名声，名望'],
  ['familiar', '熟悉的，常见的'], ['famine', '饥荒'], ['fancy', '想象，喜爱，精致的'],
  ['fantastic', '极好的，奇异的'], ['fantasy', '幻想，想象'], ['fare', '费用，票价'],
  ['fascinate', '使着迷，吸引'], ['fashion', '时尚，方式'], ['fatal', '致命的，灾难性的'],
  ['fate', '命运，宿命'], ['fatigue', '疲劳，疲乏'], ['fault', '错误，缺点'],
  ['favor', '偏爱，恩惠'], ['favorable', '有利的，赞成的'], ['feasible', '可行的，可能的'],
  ['feature', '特征，特色'], ['federal', '联邦的，联邦政府的'], ['feedback', '反馈，回馈'],
  ['fertile', '肥沃的，富饶的'], ['fiction', '小说，虚构'], ['fierce', '凶猛的，激烈的'],
  ['finance', '金融，财务'], ['financial', '金融的，财务的'], ['flavor', '风味，味道'],
  ['flexible', '灵活的，弹性的'], ['flock', '羊群，一群'], ['flourish', '繁荣，兴旺'],
  ['fluctuate', '波动，起伏'], ['fluent', '流利的，流畅的'], ['focus', '焦点，集中'],
  ['forbid', '禁止，不许'], ['forecast', '预测，预报'], ['foreign', '外国的，涉外的'],
  ['forge', '锻造，伪造'], ['formal', '正式的，形式上的'], ['format', '格式，版式'],
  ['former', '前者的，以前的'], ['formula', '公式，配方'], ['fortune', '财富，运气'],
  ['foster', '培养，促进'], ['foundation', '基础，基金会'], ['fraction', '部分，分数'],
  ['fragile', '脆弱的，易碎的'], ['fragment', '碎片，片段'], ['frame', '框架，边框'],
  ['framework', '框架，结构'], ['frank', '坦白的，直率的'], ['frequent', '频繁的，经常的'],
  ['frontier', '边境，前沿'], ['fulfill', '实现，履行'], ['function', '功能，函数'],
  ['fund', '基金，资助'], ['fundamental', '基本的，根本的'], ['furthermore', '此外，而且'],
  ['fuss', '大惊小怪，忙乱'],

  // === G (四六级) ===
  ['gamble', '赌博，冒险'], ['gap', '差距，缺口'], ['gather', '聚集，收集'],
  ['gaze', '凝视，注视'], ['gender', '性别'], ['gene', '基因'],
  ['generate', '产生，生成'], ['generous', '慷慨的，大方的'], ['genius', '天才，天赋'],
  ['genuine', '真正的，真诚的'], ['gesture', '手势，姿态'], ['global', '全球的，全面的'],
  ['globe', '地球，球体'], ['glorious', '光荣的，辉煌的'], ['glory', '光荣，荣耀'],
  ['govern', '统治，管理'], ['government', '政府'], ['grab', '抓住，抢夺'],
  ['grace', '优雅，恩惠'], ['gradual', '逐渐的，逐步的'], ['graduate', '毕业，毕业生'],
  ['grain', '谷物，颗粒'], ['grand', '宏大的，壮丽的'], ['grant', '授予，拨款'],
  ['grasp', '掌握，抓住'], ['grateful', '感激的，感谢的'], ['gratitude', '感谢，感激'],
  ['gravitation', '引力，重力'], ['greedy', '贪婪的，贪心的'], ['guarantee', '保证，担保'],
  ['guidance', '指导，引导'], ['guilty', '有罪的，内疚的'],

  // === H (四六级) ===
  ['habitat', '栖息地，生活环境'], ['halt', '停止，暂停'], ['handle', '处理，把手'],
  ['handy', '方便的，手边的'], ['harbor', '港口，庇护'], ['hardship', '困难，艰辛'],
  ['harm', '伤害，损害'], ['harmony', '和谐，协调'], ['harness', '利用，马具'],
  ['harsh', '严厉的，恶劣的'], ['harvest', '收获，收割'], ['hazard', '危险，危害'],
  ['headline', '标题，头条'], ['headquarters', '总部，司令部'], ['heal', '治愈，愈合'],
  ['heap', '堆，大量'], ['hedge', '树篱，对冲'], ['hence', '因此，从此'],
  ['heritage', '遗产，传统'], ['heroic', '英雄的，英勇的'], ['hesitate', '犹豫，迟疑'],
  ['highlight', '突出，强调，亮点'], ['hinder', '阻碍，妨碍'], ['hint', '提示，暗示'],
  ['hollow', '空的，空洞的'], ['honor', '荣誉，尊敬'], ['horizon', '地平线，眼界'],
  ['horror', '恐怖，恐惧'], ['hospitality', '好客，殷勤'], ['hostile', '敌对的，敌意的'],
  ['household', '家庭，户'], ['humble', '谦虚的，卑微的'], ['humor', '幽默，诙谐'],
  ['hydrogen', '氢'],

  // === I (四六级) ===
  ['ideal', '理想的，完美的'], ['identical', '相同的，同一的'], ['identify', '识别，鉴定'],
  ['identity', '身份，同一性'], ['idle', '空闲的，懒惰的'], ['ignorance', '无知，愚昧'],
  ['ignorant', '无知的，愚昧的'], ['ignore', '忽视，忽略'], ['illegal', '非法的，违法的'],
  ['illustrate', '说明，阐明'], ['illustration', '插图，例证'], ['image', '图像，形象'],
  ['imagination', '想象，想象力'], ['imagine', '想象，设想'], ['imitate', '模仿，仿效'],
  ['immense', '巨大的，极大的'], ['immigrant', '移民的'], ['immune', '免疫的，不受影响的'],
  ['impact', '影响，冲击'], ['implement', '实施，执行，工具'], ['implication', '含义，暗示'],
  ['imply', '暗示，意味着'], ['import', '进口，输入'], ['impose', '强加，征收'],
  ['impress', '给…留下印象'], ['impression', '印象，感觉'], ['impressive', '令人印象深刻的'],
  ['impulse', '冲动，推动力'], ['incident', '事件，事变'], ['incline', '倾向，倾斜'],
  ['income', '收入，收益'], ['incorporate', '包含，合并'], ['increasingly', '越来越多地，日益'],
  ['incredible', '难以置信的'], ['independence', '独立，自立'], ['independent', '独立的，自主的'],
  ['indicate', '表明，指出'], ['indication', '指示，迹象'], ['individual', '个人的，个体'],
  ['induce', '引起，诱导'], ['industrial', '工业的，产业的'], ['inevitable', '不可避免的'],
  ['infant', '婴儿，幼儿'], ['inferior', '劣等的，下级的'], ['inflation', '通货膨胀'],
  ['influence', '影响，作用'], ['influential', '有影响力的'], ['inform', '通知，告知'],
  ['ingredient', '成分，原料'], ['inhabit', '居住于，栖息于'], ['inherent', '固有的，内在的'],
  ['inherit', '继承，遗传'], ['initial', '最初的，初始的'], ['initiative', '主动性，倡议'],
  ['injure', '伤害，损害'], ['injury', '受伤，伤害'], ['innocent', '无辜的，天真的'],
  ['innovation', '创新，革新'], ['input', '输入，投入'], ['inquire', '询问，打听'],
  ['inquiry', '询问，调查'], ['insert', '插入，嵌入'], ['insight', '洞察力，深刻见解'],
  ['inspect', '检查，视察'], ['inspire', '激励，启发'], ['install', '安装，安置'],
  ['instance', '例子，实例'], ['instant', '立即的，瞬间的'], ['instinct', '本能，直觉'],
  ['institute', '学院，机构'], ['institution', '机构，制度'], ['instruct', '指导，指示'],
  ['instrument', '工具，乐器'], ['insurance', '保险'], ['integrate', '整合，融合'],
  ['integrity', '正直，完整'], ['intellectual', '智力的，知识分子'], ['intelligence', '智力，情报'],
  ['intelligent', '聪明的，智能的'], ['intend', '打算，计划'], ['intense', '强烈的，紧张的'],
  ['intention', '意图，打算'], ['interact', '互动，相互作用'], ['interest', '兴趣，利息'],
  ['interfere', '干涉，干扰'], ['interference', '干涉，干扰'], ['interior', '内部的，内部'],
  ['internal', '内部的，体内的'], ['interpret', '解释，口译'], ['interval', '间隔，休息时间'],
  ['intimate', '亲密的，私人的'], ['invade', '入侵，侵略'], ['invasion', '入侵，侵略'],
  ['invent', '发明，创造'], ['invention', '发明，创造'], ['invest', '投资，投入'],
  ['investigate', '调查，研究'], ['investment', '投资'], ['invisible', '看不见的，隐形的'],
  ['involve', '涉及，包含'], ['isolate', '隔离，孤立'], ['issue', '问题，议题，发行'],
  ['item', '项目，条目'],

  // === J-K (四六级) ===
  ['jealous', '嫉妒的，猜忌的'], ['joint', '联合的，关节'], ['journal', '期刊，杂志'],
  ['journalist', '记者，新闻工作者'], ['journey', '旅程，旅行'], ['judgment', '判断，审判'],
  ['junior', '年少的，下级的'], ['jury', '陪审团，评委会'], ['justice', '正义，公正'],
  ['justify', '证明…合理'], ['keen', '敏锐的，热衷的'], ['kernel', '核心，内核'],
  ['kidnap', '绑架'], ['kindergarten', '幼儿园'], ['kit', '工具箱，装备'],
  ['knowledge', '知识，学问'],

  // === L (四六级) ===
  ['label', '标签，标记'], ['laboratory', '实验室'], ['landscape', '风景，景观'],
  ['largely', '主要地，很大程度上'], ['launch', '发射，启动'], ['laundry', '洗衣房，待洗衣物'],
  ['layer', '层次，层'], ['layout', '布局，设计'], ['leadership', '领导力，领导'],
  ['league', '联盟，社团'], ['leak', '泄漏，泄露物'], ['lean', '倾斜，瘦的，精简'],
  ['leap', '跳跃，飞跃'], ['lease', '租约，租赁'], ['legal', '法定的，合法的'],
  ['legend', '传说，传奇'], ['legislation', '立法，法规'], ['legitimate', '合法的，正当的'],
  ['leisure', '空闲，闲暇'], ['lest', '以免，唯恐'], ['liable', '有责任的，易于…的'],
  ['liberal', '自由的，开明的'], ['liberate', '解放，释放'], ['liberty', '自由'],
  ['license', '执照，许可'], ['likewise', '同样地，也'], ['limb', '肢，树枝'],
  ['limitation', '限制，局限'], ['link', '链接，联系'], ['liquid', '液体，液体的'],
  ['literary', '文学的'], ['literature', '文学，文献'], ['load', '负载，装载'],
  ['loan', '贷款，借出'], ['locate', '定位，位于'], ['location', '位置，地点'],
  ['lodging', '住宿，寄宿'], ['logic', '逻辑，推理'], ['logical', '逻辑的，合理的'],
  ['loose', '松的，宽松的'], ['loyal', '忠诚的，忠心的'], ['loyalty', '忠诚，忠心'],
  ['luxury', '奢侈，奢侈品'],

  // === M (四六级) ===
  ['machinery', '机械，机器'], ['magnetic', '磁性的，有吸引力的'], ['magnificent', '壮丽的，宏伟的'],
  ['maintain', '维持，保持'], ['maintenance', '维护，保养'], ['major', '主要的，专业'],
  ['majority', '多数，大多数'], ['mankind', '人类'], ['manner', '方式，举止'],
  ['manual', '手工的，手册'], ['manufacture', '制造，生产'], ['margin', '边缘，利润空间'],
  ['marine', '海洋的，船舶的'], ['mass', '大量的，群众'], ['massive', '巨大的，大量的'],
  ['master', '大师，掌握'], ['mate', '伙伴，伴侣'], ['material', '材料，物质'],
  ['mature', '成熟的，成年'], ['maximum', '最大的，最大值'], ['mayor', '市长'],
  ['measure', '测量，措施'], ['mechanic', '机械师，技工'], ['mechanism', '机制，机械装置'],
  ['media', '媒体，媒介'], ['medium', '中等的，媒介'], ['memorial', '纪念的，纪念碑'],
  ['mental', '精神的，心理的'], ['mention', '提到，提及'], ['merchant', '商人，商户'],
  ['mercy', '仁慈，怜悯'], ['mere', '仅仅的，纯粹的'], ['merit', '优点，价值'],
  ['mild', '温和的，轻微的'], ['military', '军事的，军队'], ['minimum', '最小的，最小值'],
  ['ministry', '部门，部委'], ['minor', '次要的，较小的'], ['minority', '少数，少数民族'],
  ['miracle', '奇迹，奇事'], ['miserable', '悲惨的，痛苦的'], ['mislead', '误导，使误解'],
  ['missing', '失踪的，缺失的'], ['mission', '使命，任务'], ['misunderstand', '误解，误会'],
  ['mobile', '移动的，活动的'], ['moderate', '适度的，温和的'], ['modest', '谦虚的，适中的'],
  ['modify', '修改，更改'], ['monitor', '监视，监控器'], ['mood', '情绪，心情'],
  ['moral', '道德的，道德观'], ['moreover', '此外，而且'], ['mortal', '凡人的，致命的'],
  ['motion', '运动，动作'], ['motivate', '激励，激发'], ['motive', '动机，目的'],
  ['mount', '登上，安装'], ['multiple', '多重的，倍数'], ['multiply', '乘，倍增'],
  ['mutual', '相互的，共同的'], ['mysterious', '神秘的，难以理解的'], ['mystery', '神秘，谜'],

  // === N (四六级) ===
  ['namely', '即，也就是'], ['narrow', '狭窄的，狭隘的'], ['nasty', '令人厌恶的，恶劣的'],
  ['nationality', '国籍，民族'], ['native', '本国的，本土的'], ['navy', '海军'],
  ['necessarily', '必然地，必要地'], ['necessity', '必要性，必需品'], ['negative', '负面的，消极的'],
  ['neglect', '忽视，忽略'], ['negotiate', '谈判，协商'], ['network', '网络，关系网'],
  ['neutral', '中立的，中性的'], ['nevertheless', '然而，不过'], ['noble', '高贵的，贵族'],
  ['normal', '正常的，标准的'], ['noticeable', '明显的，显著的'], ['notify', '通知，告知'],
  ['notion', '概念，观念'], ['novel', '新颖的，小说'], ['nuclear', '核的，核能的'],
  ['nuisance', '讨厌的人/事，麻烦事'], ['numerous', '许多的，大量的'], ['nursery', '托儿所，苗圃'],

  // === O (四六级) ===
  ['objection', '反对，异议'], ['objective', '目标，客观的'], ['obligation', '义务，责任'],
  ['oblige', '迫使，施恩于'], ['observe', '观察，遵守'], ['observer', '观察者，观察员'],
  ['obstacle', '障碍，妨碍'], ['obtain', '获得，得到'], ['obvious', '明显的，显然的'],
  ['occasion', '场合，时机'], ['occasional', '偶尔的，偶然的'], ['occupy', '占据，占领'],
  ['occur', '发生，出现'], ['odd', '奇数的，古怪的'], ['offend', '冒犯，得罪'],
  ['offense', '冒犯，犯罪'], ['offer', '提供，提议'], ['official', '官方的，官员'],
  ['omit', '省略，遗漏'], ['opera', '歌剧'], ['operate', '操作，经营'],
  ['operation', '操作，手术'], ['opponent', '对手，反对者'], ['opportunity', '机会，时机'],
  ['oppose', '反对，对抗'], ['opposite', '相反的，对面'], ['optimistic', '乐观的'],
  ['option', '选择，选项'], ['orbit', '轨道，绕轨道运行'], ['organ', '器官，机构'],
  ['organic', '有机的，器官的'], ['organism', '生物，有机体'], ['organization', '组织，机构'],
  ['organize', '组织，安排'], ['origin', '起源，来源'], ['original', '原始的，最初的'],
  ['outcome', '结果，成果'], ['outlet', '出口，发泄途径'], ['outline', '概要，轮廓'],
  ['output', '产量，输出'], ['outstanding', '杰出的，突出的'], ['overcome', '克服，战胜'],
  ['overlook', '俯瞰，忽视'], ['overseas', '海外的，国外的'], ['overtake', '超过，追上'],
  ['owe', '欠，归功于'], ['ownership', '所有权，物主身份'],

  // === P (四六级) ===
  ['pace', '步伐，速度'], ['pack', '包装，打包'], ['panel', '面板，专门小组'],
  ['panic', '恐慌，惊慌'], ['parallel', '平行的，类似的'], ['parcel', '包裹，邮包'],
  ['participant', '参与者'], ['participate', '参与，参加'], ['particular', '特别的，特定的'],
  ['partly', '部分地，一定程度上'], ['partner', '伙伴，合伙人'], ['passion', '激情，热情'],
  ['passive', '被动的，消极的'], ['patent', '专利，专利权'], ['patience', '耐心，忍耐'],
  ['patient', '耐心的，病人'], ['pattern', '模式，图案'], ['payment', '付款，支付'],
  ['peak', '峰值，顶峰'], ['peculiar', '奇特的，独特的'], ['penalty', '惩罚，处罚'],
  ['penetrate', '穿透，渗透'], ['pension', '养老金，退休金'], ['perceive', '察觉，感知'],
  ['percent', '百分比'], ['perception', '感知，看法'], ['perfect', '完美的，完善的'],
  ['perform', '执行，表演'], ['performance', '性能，表现，演出'], ['permanent', '永久的，长期的'],
  ['permit', '允许，许可'], ['persist', '坚持，持续'], ['personality', '个性，人格'],
  ['personnel', '人员，员工'], ['perspective', '观点，视角'], ['pessimistic', '悲观的'],
  ['phase', '阶段，相位'], ['phenomenon', '现象，奇迹'], ['philosophy', '哲学，人生观'],
  ['physical', '物理的，身体的'], ['physician', '内科医生'], ['physicist', '物理学家'],
  ['pilot', '飞行员，试验'], ['pioneer', '先驱，先锋'], ['plague', '瘟疫，困扰'],
  ['planet', '行星'], ['plant', '植物，工厂'], ['plea', '请求，恳求，抗辩'],
  ['pledge', '承诺，誓言，抵押'], ['plenty', '大量，充足'], ['plot', '情节，密谋'],
  ['plug', '插头，塞子'], ['plunge', '投入，跳入'], ['plus', '加，加上'],
  ['poetry', '诗歌，诗'], ['poison', '毒药，毒害'], ['policy', '政策，方针'],
  ['polish', '擦亮，完善'], ['poll', '民意调查，投票'], ['pollute', '污染，弄脏'],
  ['pollution', '污染'], ['portable', '便携的，手提的'], ['portion', '部分，一份'],
  ['portrait', '肖像，画像'], ['pose', '姿势，造成，提出'], ['positive', '积极的，正面的'],
  ['possess', '拥有，具有'], ['possession', '拥有，财产'], ['potential', '潜力，潜在的'],
  ['poverty', '贫穷，贫困'], ['practical', '实用的，实际的'], ['pray', '祈祷，祷告'],
  ['precaution', '预防，防范'], ['precious', '珍贵的，宝贵的'], ['precise', '精确的，准确的'],
  ['predict', '预测，预言'], ['prefer', '更喜欢，偏好'], ['prejudice', '偏见，歧视'],
  ['preliminary', '初步的，预备的'], ['premier', '首要的，总理'], ['premise', '前提，假设'],
  ['premium', '优质的，额外费用'], ['prescribe', '开处方，规定'], ['presence', '存在，出席'],
  ['preserve', '保存，保护'], ['president', '总统，总裁，校长'], ['pressure', '压力，压强'],
  ['presume', '假定，推测'], ['prevail', '盛行，占优势'], ['previous', '先前的，以前的'],
  ['pride', '骄傲，自豪'], ['primary', '主要的，初级的'], ['prime', '首要的，最好的'],
  ['primitive', '原始的，简单的'], ['principal', '主要的，校长'], ['principle', '原则，原理'],
  ['priority', '优先，优先权'], ['privacy', '隐私，私密'], ['private', '私人的，私营的'],
  ['privilege', '特权，优惠'], ['procedure', '程序，步骤'], ['proceed', '继续，进行'],
  ['process', '过程，处理'], ['proclaim', '宣告，宣布'], ['produce', '生产，产生'],
  ['productive', '多产的，富有成效的'], ['productivity', '生产力，生产效率'], ['profession', '职业，专业'],
  ['professional', '专业的，职业的'], ['profit', '利润，盈利'], ['profound', '深刻的，深奥的'],
  ['program', '程序，计划'], ['prohibit', '禁止，阻止'], ['project', '项目，投射'],
  ['prominent', '突出的，杰出的'], ['promise', '承诺，许诺'], ['promote', '促进，推广，晋升'],
  ['promotion', '促进，晋升'], ['prompt', '迅速的，提示'], ['proof', '证据，证明'],
  ['proper', '适当的，正确的'], ['property', '财产，性质'], ['proportion', '比例，部分'],
  ['proposal', '提议，建议'], ['propose', '提议，建议'], ['prospect', '前景，展望'],
  ['prosperity', '繁荣，兴旺'], ['protect', '保护，防护'], ['protein', '蛋白质'],
  ['protest', '抗议，反对'], ['prove', '证明，证实'], ['provide', '提供，供应'],
  ['province', '省份，领域'], ['provision', '规定，供应，预备'], ['psychological', '心理的，心理学的'],
  ['publication', '出版，出版物'], ['publicity', '宣传，知名度'], ['publish', '出版，发布'],
  ['pulse', '脉搏，脉冲'], ['pump', '泵，抽水'], ['punctual', '准时的，守时的'],
  ['purchase', '购买，采购'], ['pursue', '追求，追赶'], ['pursuit', '追求，追赶'],
  ['puzzle', '谜，困惑，使困惑'],

  // === Q-R (四六级) ===
  ['qualification', '资格，条件'], ['qualify', '使合格，限定'], ['quantity', '数量，量'],
  ['quest', '探索，寻求'], ['quit', '辞职，退出'], ['quotation', '报价，引文'],
  ['quote', '引用，报价'], ['racial', '种族的，人种的'], ['radical', '激进的，根本的'],
  ['rail', '铁路，栏杆'], ['random', '随机的，随意的'], ['range', '范围，山脉，排列'],
  ['rank', '排名，等级'], ['rapid', '迅速的，快的'], ['rare', '稀有的，罕见的'],
  ['rate', '比率，费率，评价'], ['ratio', '比率，比例'], ['rational', '理性的，合理的'],
  ['raw', '生的，未加工的'], ['react', '反应，作出反应'], ['readily', '容易地，乐意地'],
  ['realistic', '现实的，实际的'], ['reality', '现实，实际'], ['realize', '意识到，实现'],
  ['realm', '领域，王国'], ['rear', '后面，后方'], ['reasonable', '合理的，公道的'],
  ['rebel', '反叛者，造反'], ['recall', '回忆，召回'], ['receipt', '收据，收到'],
  ['receive', '收到，接收'], ['recent', '最近的，近来的'], ['reception', '接待，接收'],
  ['recession', '衰退，不景气'], ['reckon', '认为，估算'], ['recognition', '认出，承认'],
  ['recognize', '认出，承认'], ['recommend', '推荐，建议'], ['recommendation', '推荐，建议'],
  ['reconcile', '调和，和解'], ['recover', '恢复，康复'], ['recovery', '恢复，痊愈'],
  ['recreation', '娱乐，消遣'], ['recruit', '招募，新成员'], ['reduce', '减少，缩减'],
  ['reduction', '减少，缩减'], ['refer', '参考，提到'], ['reference', '参考，参考文献'],
  ['reflect', '反映，反射，反思'], ['reflection', '反映，反射，反思'], ['reform', '改革，改良'],
  ['refresh', '使恢复精力，刷新'], ['refuge', '避难，庇护'], ['refugee', '难民'],
  ['refund', '退款，退还'], ['refuse', '拒绝'], ['regard', '视为，尊重，问候'],
  ['regarding', '关于，至于'], ['regardless', '不管，不顾'], ['region', '地区，区域'],
  ['register', '注册，登记'], ['regulate', '调节，管理'], ['regulation', '规章，规则'],
  ['reinforce', '加强，强化'], ['reject', '拒绝，排斥'], ['relate', '联系，叙述'],
  ['relation', '关系，联系'], ['relationship', '关系，关联'], ['relative', '相对的，亲戚'],
  ['relax', '放松，松弛'], ['release', '释放，发布'], ['relevant', '相关的，切题的'],
  ['reliable', '可靠的，可信赖的'], ['relief', '减轻，救济'], ['relieve', '减轻，解除'],
  ['religion', '宗教，信仰'], ['religious', '宗教的，虔诚的'], ['reluctant', '不情愿的，勉强的'],
  ['rely', '依靠，依赖'], ['remain', '保持，剩余'], ['remark', '评论，注意'],
  ['remarkable', '引人注目的，非凡的'], ['remedy', '补救，治疗'], ['remote', '遥远的，偏僻的'],
  ['removal', '除去，搬迁'], ['remove', '移除，删除'], ['render', '提供，渲染，使成为'],
  ['renew', '更新，续借'], ['rent', '租金，出租'], ['replace', '替换，取代'],
  ['represent', '代表，表示'], ['representative', '代表，代表性的'], ['reputation', '名誉，名声'],
  ['request', '请求，要求'], ['require', '需要，要求'], ['rescue', '救援，营救'],
  ['research', '研究，调查'], ['resemble', '像，类似于'], ['reservation', '预订，保留意见'],
  ['reserve', '预订，保留'], ['resign', '辞职，放弃'], ['resist', '抵抗，抗拒'],
  ['resistance', '抵抗，阻力'], ['resolution', '决议，决心，分辨率'], ['resolve', '解决，决心'],
  ['resort', '度假胜地，求助'], ['resource', '资源，财力'], ['respond', '回应，响应'],
  ['response', '回应，答复'], ['responsibility', '责任，职责'], ['responsible', '有责任的，负责的'],
  ['restore', '恢复，修复'], ['restrain', '抑制，限制'], ['restrict', '限制，约束'],
  ['retain', '保留，保持'], ['retire', '退休，退役'], ['retreat', '撤退，退却'],
  ['reveal', '显示，揭露'], ['revenue', '收入，税收'], ['reverse', '反向的，逆转'],
  ['review', '回顾，复习，评论'], ['revise', '修订，修改'], ['revolt', '起义，反抗'],
  ['revolution', '革命，变革'], ['reward', '奖励，回报'], ['ridiculous', '荒谬的，可笑的'],
  ['rigid', '严格的，僵硬的'], ['ripe', '成熟的'], ['risk', '风险，危险'],
  ['rival', '竞争对手，敌对的'], ['roar', '吼叫，咆哮'], ['robot', '机器人'],
  ['root', '根，根源'], ['rotate', '旋转，轮换'], ['rough', '粗糙的，粗略的'],
  ['routine', '常规，例行公事'], ['row', '行，排，划船'], ['royal', '皇家的，王室的'],
  ['ruin', '毁坏，废墟'], ['rural', '农村的，乡村的'], ['rush', '冲，匆忙'],

  // === S (四六级) ===
  ['sacrifice', '牺牲，献出'], ['sake', '缘故，目的'], ['salary', '薪水，工资'],
  ['sample', '样品，样本'], ['sanction', '制裁，批准'], ['satellite', '卫星'],
  ['satisfactory', '令人满意的'], ['satisfy', '使满意，满足'], ['scale', '规模，比例，刻度'],
  ['scan', '扫描，浏览'], ['scandal', '丑闻，丢脸'], ['scarce', '缺乏的，稀少的'],
  ['scatter', '分散，散开'], ['scene', '场景，景色'], ['schedule', '时间表，安排'],
  ['scheme', '方案，计划，阴谋'], ['scholar', '学者'], ['scholarship', '奖学金，学术'],
  ['scope', '范围，眼界'], ['scratch', '抓，挠，划痕'], ['screen', '屏幕，筛查'],
  ['seal', '密封，印章'], ['secondary', '次要的，中学的'], ['section', '部分，部门'],
  ['sector', '部门，行业'], ['secure', '安全的，获得'], ['security', '安全，保安'],
  ['seek', '寻求，寻找'], ['seize', '抓住，夺取'], ['select', '选择，挑选'],
  ['semester', '学期'], ['seminar', '研讨会，讨论班'], ['senior', '高级的，年长的'],
  ['sensation', '感觉，轰动'], ['sense', '感觉，意义'], ['sensible', '明智的，合理的'],
  ['sensitive', '敏感的，灵敏的'], ['separate', '分开，分离'], ['sequence', '顺序，序列'],
  ['series', '系列，连续'], ['session', '会议，一段时间'], ['settle', '解决，定居'],
  ['severe', '严重的，严厉的'], ['shallow', '浅的，肤浅的'], ['shame', '羞愧，耻辱'],
  ['shape', '形状，塑造'], ['share', '分享，份额'], ['shatter', '粉碎，破灭'],
  ['shell', '壳，贝壳'], ['shelter', '庇护，住所'], ['shield', '盾，防护'],
  ['shift', '转移，轮班'], ['shortage', '短缺，不足'], ['shrink', '缩小，退缩'],
  ['signal', '信号，标志'], ['signature', '签名，署名'], ['significance', '意义，重要性'],
  ['significant', '重要的，有意义的'], ['simplify', '简化，精简'], ['sincere', '真诚的，真挚的'],
  ['site', '地点，场所'], ['situation', '情况，处境'], ['sketch', '素描，草图'],
  ['skill', '技能，技巧'], ['slight', '轻微的，纤细的'], ['slip', '滑倒，失误'],
  ['slogan', '口号，标语'], ['smash', '打碎，粉碎'], ['soar', '飙升，高飞'],
  ['social', '社会的，社交的'], ['sole', '唯一的，单独的'], ['solemn', '庄严的，严肃的'],
  ['solid', '固体的，坚固的'], ['solution', '解决方案，溶液'], ['somewhat', '有点，稍微'],
  ['sophisticated', '精密的，老练的'], ['sorrow', '悲伤，悲痛'], ['source', '来源，出处'],
  ['span', '跨度，一段时间'], ['spark', '火花，引发'], ['specialist', '专家，专科医生'],
  ['specialize', '专门从事，专攻'], ['species', '物种，种类'], ['specific', '具体的，特定的'],
  ['specimen', '标本，样品'], ['spectacle', '景象，壮观'], ['spectacular', '壮观的，惊人的'],
  ['speculate', '推测，投机'], ['sphere', '球体，领域'], ['spill', '溢出，洒出'],
  ['spin', '旋转，纺纱'], ['spiritual', '精神的，心灵的'], ['split', '分裂，分开'],
  ['spoil', '破坏，宠坏'], ['sponsor', '赞助者，赞助'], ['spot', '地点，斑点，发现'],
  ['spread', '传播，扩散'], ['squeeze', '挤压，榨取'], ['stable', '稳定的，马厩'],
  ['staff', '员工，全体工作人员'], ['stain', '污点，染色'], ['stake', '利害关系，赌注'],
  ['standard', '标准，规范'], ['stare', '凝视，盯着看'], ['starve', '挨饿，饿死'],
  ['statement', '陈述，声明'], ['statistics', '统计，统计学'], ['status', '地位，状态'],
  ['steady', '稳定的，稳固的'], ['steep', '陡峭的，过高的'], ['steer', '驾驶，引导'],
  ['stem', '茎，起源于'], ['stick', '棍子，粘贴，坚持'], ['stimulate', '刺激，激励'],
  ['stir', '搅拌，激起'], ['stock', '股票，库存'], ['strain', '压力，拉紧，品系'],
  ['strategy', '策略，战略'], ['stream', '溪流，流动'], ['strength', '力量，强度'],
  ['strengthen', '加强，增强'], ['stress', '压力，强调'], ['stretch', '伸展，延伸'],
  ['strike', '罢工，打击'], ['strip', '条，带，剥夺'], ['stroke', '中风，击打，笔划'],
  ['structure', '结构，构造'], ['struggle', '斗争，挣扎'], ['stuff', '东西，填满'],
  ['subject', '主题，科目，受…影响的'], ['subjective', '主观的'], ['submit', '提交，服从'],
  ['subsequent', '随后的，后来的'], ['substance', '物质，实质'], ['substantial', '大量的，实质的'],
  ['substitute', '代替，替代品'], ['subtle', '微妙的，精细的'], ['suburb', '郊区，市郊'],
  ['succeed', '成功，继承'], ['succession', '连续，继承'], ['suck', '吸，吮吸'],
  ['suffer', '遭受，受苦'], ['sufficient', '足够的，充分的'], ['suggest', '建议，暗示'],
  ['suggestion', '建议，暗示'], ['suicide', '自杀'], ['suitable', '合适的，适当的'],
  ['sum', '总和，金额'], ['summarize', '总结，概括'], ['summary', '摘要，总结'],
  ['summit', '顶点，峰会'], ['superb', '极好的，出色的'], ['superficial', '表面的，肤浅的'],
  ['superior', '优秀的，上级的'], ['supervise', '监督，管理'], ['supplement', '补充，增刊'],
  ['supply', '供应，供给'], ['support', '支持，供养'], ['suppose', '假设，认为'],
  ['supreme', '最高的，极度的'], ['surface', '表面，外表'], ['surgery', '外科，手术'],
  ['surplus', '过剩，盈余'], ['surrender', '投降，放弃'], ['surround', '围绕，包围'],
  ['surrounding', '周围的，环境'], ['survey', '调查，测量'], ['survive', '幸存，存活'],
  ['survivor', '幸存者'], ['suspect', '怀疑，嫌疑犯'], ['suspend', '暂停，悬挂'],
  ['suspicion', '怀疑，猜疑'], ['suspicious', '可疑的，怀疑的'], ['sustain', '维持，支撑'],
  ['swallow', '吞咽，燕子'], ['swear', '发誓，咒骂'], ['sweep', '打扫，席卷'],
  ['swell', '膨胀，肿胀'], ['swift', '迅速的，敏捷的'], ['swing', '摇摆，秋千'],
  ['switch', '开关，转换'], ['symbol', '象征，符号'], ['sympathetic', '同情的，共鸣的'],
  ['sympathy', '同情，怜悯'], ['symptom', '症状，征兆'], ['synthetic', '合成的，人造的'],
  ['system', '系统，体系'],

  // === T (四六级) ===
  ['tackle', '处理，解决，装备'], ['talent', '天才，才能'], ['target', '目标，对象'],
  ['technique', '技术，技巧'], ['technology', '技术，科技'], ['tedious', '冗长的，乏味的'],
  ['teenager', '青少年'], ['telescope', '望远镜'], ['temper', '脾气，情绪'],
  ['temporary', '临时的，暂时的'], ['tempt', '诱惑，引诱'], ['tend', '倾向于，照顾'],
  ['tendency', '倾向，趋势'], ['tender', '温柔的，嫩的'], ['tense', '紧张的，拉紧的'],
  ['tension', '紧张，张力'], ['terminal', '终点的，终端'], ['territory', '领土，领域'],
  ['terror', '恐怖，惊骇'], ['textile', '纺织品'], ['theme', '主题，话题'],
  ['theory', '理论，学说'], ['therapy', '治疗，疗法'], ['therefore', '因此，所以'],
  ['thorough', '彻底的，详尽的'], ['thought', '思想，思考'], ['threat', '威胁，恐吓'],
  ['threaten', '威胁，恐吓'], ['thrill', '激动，兴奋'], ['thrive', '繁荣，茁壮成长'],
  ['through', '通过，穿过'], ['thus', '因此，从而'], ['tide', '潮汐，潮流'],
  ['tight', '紧的，牢固的'], ['tissue', '组织，纸巾'], ['tolerate', '容忍，忍受'],
  ['tone', '语气，音调'], ['topic', '主题，话题'], ['torture', '折磨，拷问'],
  ['tough', '艰苦的，强硬的'], ['trace', '追踪，痕迹'], ['track', '轨道，追踪'],
  ['tradition', '传统，惯例'], ['traditional', '传统的'], ['tragedy', '悲剧，灾难'],
  ['trail', '小径，踪迹'], ['transfer', '转移，调动'], ['transform', '改变，转换'],
  ['transformation', '转变，改革'], ['transmit', '传输，传播'], ['transparent', '透明的，明显的'],
  ['transport', '运输，交通'], ['trap', '陷阱，陷阱'], ['treasure', '财富，珍爱'],
  ['treat', '对待，治疗'], ['treaty', '条约，协议'], ['tremble', '发抖，颤抖'],
  ['trend', '趋势，倾向'], ['trial', '试验，审判'], ['tribe', '部落，族群'],
  ['trick', '诡计，恶作剧'], ['trigger', '触发，引起'], ['trim', '修剪，整齐的'],
  ['triumph', '胜利，成功'], ['troop', '部队，一群'], ['tropical', '热带的'],
  ['trouble', '麻烦，困扰'], ['trust', '信任，托付'], ['tuition', '学费，教学'],
  ['tune', '曲调，调整'], ['tunnel', '隧道，地道'], ['tutor', '导师，家教'],
  ['typical', '典型的，有代表性的'], ['tyre', '轮胎'],

  // === U (四六级) ===
  ['ultimate', '最终的，根本的'], ['undergo', '经历，遭受'], ['undergraduate', '本科生'],
  ['underline', '在…下划线，强调'], ['underlying', '潜在的，根本的'], ['undermine', '破坏，削弱'],
  ['undertake', '承担，着手做'], ['unemployment', '失业'], ['unexpected', '意外的，未料到的'],
  ['unfair', '不公平的'], ['unfold', '展开，呈现'], ['unfortunate', '不幸的'],
  ['unique', '独特的，唯一的'], ['unite', '团结，联合'], ['unity', '团结，统一'],
  ['universal', '普遍的，全体的'], ['universe', '宇宙，世界'], ['unlike', '不像，不同于'],
  ['unusual', '不寻常的'], ['update', '更新，刷新'], ['upper', '上面的，较高的'],
  ['upset', '使不安，打乱'], ['urban', '城市的，都市的'], ['urge', '催促，强烈欲望'],
  ['urgent', '紧急的，急迫的'], ['utilize', '利用，使用'], ['utmost', '极度的，最大的'],

  // === V (四六级) ===
  ['vacant', '空的，空缺的'], ['vague', '模糊的，含糊的'], ['vain', '徒劳的，自负的'],
  ['valid', '有效的，合理的'], ['value', '价值，重视'], ['vanish', '消失，消散'],
  ['variable', '可变的，变量'], ['variation', '变化，变动'], ['variety', '多样性，种类'],
  ['various', '各种各样的'], ['vast', '广阔的，大量的'], ['vehicle', '车辆，交通工具'],
  ['venture', '冒险，企业'], ['verify', '验证，核实'], ['version', '版本，说法'],
  ['versus', '对，与…相对'], ['vertical', '垂直的，竖的'], ['vessel', '船，血管，容器'],
  ['veteran', '老兵，经验丰富的'], ['via', '通过，经由'], ['vibrate', '振动，颤动'],
  ['vice', '恶习，副的'], ['victim', '受害者，牺牲者'], ['view', '视野，观点，看待'],
  ['viewpoint', '观点，视角'], ['vigorous', '有力的，精力充沛的'], ['violate', '违反，侵犯'],
  ['violence', '暴力，猛烈'], ['violent', '暴力的，剧烈的'], ['virtual', '虚拟的，实质上的'],
  ['virtue', '美德，优点'], ['visible', '可见的，明显的'], ['vision', '视野，视力，愿景'],
  ['visual', '视觉的，可视的'], ['vital', '至关重要的'], ['vivid', '生动的，鲜明的'],
  ['vocabulary', '词汇，词汇量'], ['volume', '体积，音量，卷'], ['voluntary', '自愿的，主动的'],
  ['volunteer', '志愿者，自愿'], ['vote', '投票，表决'], ['voyage', '航程，旅行'],

  // === W (四六级) ===
  ['wage', '工资，进行'], ['wander', '漫步，徘徊'], ['warn', '警告，提醒'],
  ['warrant', '授权令，保证'], ['wealth', '财富，富裕'], ['wealthy', '富有的，富裕的'],
  ['weapon', '武器，兵器'], ['welfare', '福利，幸福'], ['whereas', '然而，鉴于'],
  ['widespread', '广泛的，普遍的'], ['willing', '乐意的，自愿的'], ['wisdom', '智慧，明智'],
  ['withdraw', '撤回，退出'], ['withstand', '承受，抵抗'], ['witness', '目击者，证人，见证'],
  ['wonder', '惊奇，想知道'], ['workshop', '车间，研讨会'], ['worldwide', '全球的，世界范围的'],
  ['worship', '崇拜，敬奉'], ['worthwhile', '值得的，有价值的'], ['worthy', '值得的，可敬的'],
  ['wrap', '包裹，缠绕'], ['wreck', '失事，毁坏'], ['wrinkle', '皱纹，皱褶'],

  // === Y-Z (四六级) ===
  ['yield', '产出，屈服'], ['youth', '青年，青春'], ['zeal', '热情，热心'],
  ['zone', '地带，区域']
];

// 构建干扰项：从非当前单词的完整列表中随机选取 3 个单词
const allWords = words.map(w => w[0]);

function getDistractors(correct) {
  const pool = allWords.filter(w => w !== correct);
  const result = [];
  while (result.length < 3) {
    const idx = Math.floor(Math.random() * pool.length);
    result.push(pool[idx]);
    pool.splice(idx, 1);
  }
  return JSON.stringify(result);
}

async function migrateWords() {
  // 确保 word_bank 表存在（兼容不同初始化时序）
  await pool.execute(`CREATE TABLE IF NOT EXISTS word_bank (
    id INT AUTO_INCREMENT PRIMARY KEY,
    word VARCHAR(100) NOT NULL,
    meaning VARCHAR(255) NOT NULL,
    options JSON,
    UNIQUE KEY uk_word (word)
  )`);

  // 检查 word_bank 是否已有数据
  const [existing] = await pool.execute('SELECT COUNT(*) AS cnt FROM word_bank');
  if (existing[0].cnt > 0) {
    console.log(`word_bank 已有 ${existing[0].cnt} 个单词，跳过填充`);
    return;
  }

  console.log('word_bank 为空，正在填充 CET-4/CET-6 词汇...');

  let count = 0;
  for (const [word, meaning] of words) {
    const options = getDistractors(word);
    try {
      await pool.execute(
        'INSERT IGNORE INTO word_bank (word, meaning, options) VALUES (?, ?, ?)',
        [word, meaning, options]
      );
      count++;
    } catch (e) {
      console.error(`插入单词 ${word} 失败:`, e.message);
    }
  }

  console.log(`已向 word_bank 填充 ${count} 个 CET-4/CET-6 单词`);
}

module.exports = migrateWords;
